// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyTransfer.Infrastructure.Data;

#nullable disable

namespace MoneyTransfer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251111134607_AddUser")]
    partial class AddUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoneyTransfer.CoreBusiness.Models.BankAcount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Balance")
                        .HasColumnType("float")
                        .HasAnnotation("RangeMax", 1.7976931348623157E+308)
                        .HasAnnotation("RangeMin", 0);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 10000000.0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Balance = 25000000.0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Balance = 5000000.0,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("MoneyTransfer.CoreBusiness.Models.Transaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("float")
                        .HasAnnotation("RangeMax", 1.7976931348623157E+308)
                        .HasAnnotation("RangeMin", 0);

                    b.Property<double>("BalanceAfter")
                        .HasColumnType("float")
                        .HasAnnotation("RangeMax", 1.7976931348623157E+308)
                        .HasAnnotation("RangeMin", 0);

                    b.Property<double>("BalanceBefore")
                        .HasColumnType("float")
                        .HasAnnotation("RangeMax", 1.7976931348623157E+308)
                        .HasAnnotation("RangeMin", 0);

                    b.Property<Guid>("Number")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransactionTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MoneyTransfer.CoreBusiness.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@email.com",
                            FirstName = "Rayan",
                            LastName = "Reynolds",
                            PasswordHash = new byte[] { 230, 238, 118, 217, 85, 135, 110, 189, 117, 121, 10, 67, 49, 64, 166, 190, 254, 32, 246, 145, 194, 145, 196, 255, 171, 4, 14, 1, 42, 20, 68, 160, 59, 232, 16, 148, 18, 99, 141, 9, 165, 60, 72, 160, 243, 59, 230, 221, 32, 229, 255, 14, 96, 14, 84, 12, 74, 148, 104, 251, 117, 127, 18, 131 },
                            PasswordSalt = new byte[] { 116, 64, 92, 102, 127, 9, 84, 253, 61, 41, 68, 33, 234, 59, 171, 78, 138, 107, 117, 221, 211, 138, 190, 125, 200, 214, 240, 12, 86, 239, 234, 184, 129, 196, 164, 87, 197, 135, 47, 75, 0, 135, 41, 138, 220, 206, 44, 164, 179, 45, 103, 13, 249, 118, 66, 93, 215, 35, 42, 200, 13, 47, 71, 10, 234, 230, 109, 79, 156, 80, 209, 72, 57, 133, 94, 165, 76, 70, 14, 100, 171, 217, 154, 65, 228, 161, 56, 90, 136, 149, 36, 159, 76, 121, 225, 107, 151, 23, 204, 215, 227, 107, 253, 197, 72, 32, 196, 48, 4, 219, 226, 197, 171, 63, 238, 157, 211, 65, 3, 54, 179, 42, 144, 47, 204, 55, 193, 24 },
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@email.com",
                            FirstName = "Emma",
                            LastName = "Stone",
                            PasswordHash = new byte[] { 230, 238, 118, 217, 85, 135, 110, 189, 117, 121, 10, 67, 49, 64, 166, 190, 254, 32, 246, 145, 194, 145, 196, 255, 171, 4, 14, 1, 42, 20, 68, 160, 59, 232, 16, 148, 18, 99, 141, 9, 165, 60, 72, 160, 243, 59, 230, 221, 32, 229, 255, 14, 96, 14, 84, 12, 74, 148, 104, 251, 117, 127, 18, 131 },
                            PasswordSalt = new byte[] { 116, 64, 92, 102, 127, 9, 84, 253, 61, 41, 68, 33, 234, 59, 171, 78, 138, 107, 117, 221, 211, 138, 190, 125, 200, 214, 240, 12, 86, 239, 234, 184, 129, 196, 164, 87, 197, 135, 47, 75, 0, 135, 41, 138, 220, 206, 44, 164, 179, 45, 103, 13, 249, 118, 66, 93, 215, 35, 42, 200, 13, 47, 71, 10, 234, 230, 109, 79, 156, 80, 209, 72, 57, 133, 94, 165, 76, 70, 14, 100, 171, 217, 154, 65, 228, 161, 56, 90, 136, 149, 36, 159, 76, 121, 225, 107, 151, 23, 204, 215, 227, 107, 253, 197, 72, 32, 196, 48, 4, 219, 226, 197, 171, 63, 238, 157, 211, 65, 3, 54, 179, 42, 144, 47, 204, 55, 193, 24 },
                            PhoneNumber = "234-567-8901"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user3@email.com",
                            FirstName = "Chris",
                            LastName = "Evans",
                            PasswordHash = new byte[] { 230, 238, 118, 217, 85, 135, 110, 189, 117, 121, 10, 67, 49, 64, 166, 190, 254, 32, 246, 145, 194, 145, 196, 255, 171, 4, 14, 1, 42, 20, 68, 160, 59, 232, 16, 148, 18, 99, 141, 9, 165, 60, 72, 160, 243, 59, 230, 221, 32, 229, 255, 14, 96, 14, 84, 12, 74, 148, 104, 251, 117, 127, 18, 131 },
                            PasswordSalt = new byte[] { 116, 64, 92, 102, 127, 9, 84, 253, 61, 41, 68, 33, 234, 59, 171, 78, 138, 107, 117, 221, 211, 138, 190, 125, 200, 214, 240, 12, 86, 239, 234, 184, 129, 196, 164, 87, 197, 135, 47, 75, 0, 135, 41, 138, 220, 206, 44, 164, 179, 45, 103, 13, 249, 118, 66, 93, 215, 35, 42, 200, 13, 47, 71, 10, 234, 230, 109, 79, 156, 80, 209, 72, 57, 133, 94, 165, 76, 70, 14, 100, 171, 217, 154, 65, 228, 161, 56, 90, 136, 149, 36, 159, 76, 121, 225, 107, 151, 23, 204, 215, 227, 107, 253, 197, 72, 32, 196, 48, 4, 219, 226, 197, 171, 63, 238, 157, 211, 65, 3, 54, 179, 42, 144, 47, 204, 55, 193, 24 }
                        });
                });

            modelBuilder.Entity("MoneyTransfer.CoreBusiness.Models.BankAcount", b =>
                {
                    b.HasOne("MoneyTransfer.CoreBusiness.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyTransfer.CoreBusiness.Models.Transaction", b =>
                {
                    b.HasOne("MoneyTransfer.CoreBusiness.Models.BankAcount", "Acount")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acount");
                });

            modelBuilder.Entity("MoneyTransfer.CoreBusiness.Models.User", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
