// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyTransfer.Infrastructure.Data;

#nullable disable

namespace MoneyTransfer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoneyTransfer.CoreBusiness.Models.BankAcount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Balance")
                        .HasColumnType("float")
                        .HasAnnotation("RangeMax", 1.7976931348623157E+308)
                        .HasAnnotation("RangeMin", 0);

                    b.HasKey("Id");

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 10000000.0
                        },
                        new
                        {
                            Id = 2,
                            Balance = 25000000.0
                        },
                        new
                        {
                            Id = 3,
                            Balance = 5000000.0
                        });
                });

            modelBuilder.Entity("MoneyTransfer.CoreBusiness.Models.Transaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("float")
                        .HasAnnotation("RangeMax", 1.7976931348623157E+308)
                        .HasAnnotation("RangeMin", 0);

                    b.Property<double>("BalanceAfter")
                        .HasColumnType("float")
                        .HasAnnotation("RangeMax", 1.7976931348623157E+308)
                        .HasAnnotation("RangeMin", 0);

                    b.Property<double>("BalanceBefore")
                        .HasColumnType("float")
                        .HasAnnotation("RangeMax", 1.7976931348623157E+308)
                        .HasAnnotation("RangeMin", 0);

                    b.Property<Guid>("Number")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransactionTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MoneyTransfer.CoreBusiness.Models.Transaction", b =>
                {
                    b.HasOne("MoneyTransfer.CoreBusiness.Models.BankAcount", "Acount")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acount");
                });
#pragma warning restore 612, 618
        }
    }
}
